// created an array object with seven quotes
var quotes = [
  {
    quote: "Words are easy, like the wind; Faithful friends are hard to find.",
    source: "William Shakespeare",
    citation: "British poet and playwright",
    year: 1616,
    category: "Friendship",
  },
  {
    quote: "Chose a job you love, and you will never have to work a day in your life.",
    source: "Confucius",
    citation: "Chinese philosopher",
    year: "BC 479",
    category: "Work",
  },
  {
    quote: "You must be the change you wish to see in the world.",
    source: "Mahatma Gandhi",
    citation: "Preeminent leader of Indian nationalism",
    year: 1948,
    category: "Change",
  },
  {
    quote: "The true sign of intelligence is not knowledge but imagination.",
    source: "Albert Einstein",
    citation: "German-Swiss-U.S. scientist",
    year: 1955,
    category: "Intelligence",
  },
  {
    quote: "Love is the beauty of the soul.",
    source: "Saint Augustine",
    citation: "Theologian",
    year: "BC 430",
    category: "Love",
  },
  {
    quote: "Our greatest glory is not in never falling, but in rising every time we fall.",
    source: "Confucius",
    citation: "Chinese philosopher",
    year: "BC 479",
    category: "Failure",
  },
  {
    quote: "Better to remain silent and be thought a fool, than to speak and remove all doubt.",
    source: "Abraham Lincoln",
    citation: "Politician. President of the United States",
    year: 1865,
    category: "Fool",
  },
  {
    quote: "Initiative is doing the right thing without being told.",
    source: "Victor Hugo",
    citation: "French poet, dramatist and novelist",
    year: "1885",
    category: "Action",
  },
  {
    quote: "If you have knowledge, let others light their candles with it.",
    source: "Winston Churchill",
    citation: "Winston Churchill",
    year: "1965",
    category: "",
  },
  {
    quote: "The roots of education are bitter, but the fruit is sweet.",
    source: "Aristotle",
    citation: "Greek philosopher",
    year: "",
    category: "Education",
  },
  {
    quote: "The best way to make children good is to make them happy.",
    source: "",
    citation: "Irish poet and dramatist",
    year: "1900",
    category: "Children",
  },
  {
    quote: "Courage leads to heaven; fear leads to death.",
    source: "",
    citation: "Roman philosopher and playwright",
    year: "BC 65",
    category: "Courage",
  },
  {
    quote: "If you tell the truth, you don't have to remember anything.",
    source: "Mark Twain",
    citation: "U.S. humorist, writer, and lecturer",
    year: 1910,
    category: "Truth",
  },
  {
    quote: "If a man hasn't discovered something that he will die for, he isn't fit to live.",
    source: "Martin Luther King Jr",
    citation: "American black leader",
    year: "",
    category: "Death",
  },
  {
    quote: "It is prosperity that gives us friends, adversity that proves them.",
    source: "Proverb",
    citation: "",
    year: "BC 200",
    category: "Friendship",
  },
  {
    quote: "The best part of beauty is that which no picture can express.",
    source: "Francis Bacon",
    citation: "",
    year: 1926,
    category: "Beauty",
  },
  {
    quote: "A friend is a person with whom I may be sincere. Before him, I may think aloud.",
    source: "Ralph Waldo Emerson",
    citation: "U.S. poet, essayist and lecturer",
    year: "",
    category: "Friendship",
  },
]
